// This file is autogenerated. Changes will be overwritten.
#include <U3KM7JFWRN/moc_agorartcengine.cpp>
#include <GYHPFG4CL2/moc_window-agora-main.cpp>
#include <GYHPFG4CL2/moc_window-agora-settings.cpp>
